knpu_oauth2_client:
    clients:
        microsoft:
            type: azure
            client_id: '%env(OAUTH_MICROSOFT_CLIENT_ID)%'
            client_secret: '%env(OAUTH_MICROSOFT_CLIENT_SECRET)%'
            redirect_route: connect_microsoft_check
            redirect_params: {}
            tenant: '%env(OAUTH_MICROSOFT_TENANT)%'
            use_state: true
            scope:
                - openid
                - profile
                - email
                - offline_access
                - User.Read
