security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            security: true  # le firewall est actif
            stateless: false  # garde la session active

            # Authentification via formulaire classique
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_accueil

            # Authentification Microsoft OAuth2
            custom_authenticators:
                - App\Security\MicrosoftAuthenticator

            logout:
                path: app_logout
                # target: app_home

access_control:
        - { path: ^/connect/microsoft, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }


        # Routes protégées
        - { path: ^/calculette, roles: ROLE_MANAGER }
        - { path: ^/admin/users, roles: ROLE_ADMIN }
